// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLrEchIzuDvNwJh-E7BmN6kjkhHsgLVWU',
    appId: '1:1024606561667:web:2798eb5e2a9010f74f82b6',
    messagingSenderId: '1024606561667',
    projectId: 'reddit-clone-289c2',
    authDomain: 'reddit-clone-289c2.firebaseapp.com',
    storageBucket: 'reddit-clone-289c2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9XjppHoh5gXXQZ4Lmdwto7_esr28d6pQ',
    appId: '1:1024606561667:android:72c2d04a2fa5b3394f82b6',
    messagingSenderId: '1024606561667',
    projectId: 'reddit-clone-289c2',
    storageBucket: 'reddit-clone-289c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfeGYiELvCRxjF6xbAoVJJD87XJtUeuaA',
    appId: '1:1024606561667:ios:4c64afb24f868d884f82b6',
    messagingSenderId: '1024606561667',
    projectId: 'reddit-clone-289c2',
    storageBucket: 'reddit-clone-289c2.appspot.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLrEchIzuDvNwJh-E7BmN6kjkhHsgLVWU',
    appId: '1:1024606561667:web:479d53b8098bff294f82b6',
    messagingSenderId: '1024606561667',
    projectId: 'reddit-clone-289c2',
    authDomain: 'reddit-clone-289c2.firebaseapp.com',
    storageBucket: 'reddit-clone-289c2.appspot.com',
  );
}
